<a href="https://colab.research.google.com/github/2400030303/AI-LEARNINGS-WITH-PYTHON-STARTERS/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


* numpy=numerical python
Python list:

numbers = [10, 20, 30, 40]

NumPy array:

import numpy as np
numbers=np.array([10,20,30,40])



Why NumPy?

NumPy arrays are designed for numerical computation and allow us to perform operations efficiently without writing loops for every calculation.

In [1]:
# python list
numbers=[10,20,30,40]
print(numbers*2)

[10, 20, 30, 40, 10, 20, 30, 40]


In [2]:
#Numpy
import numpy as np
numbers=np.array([10,20,30,40])
print(numbers*2)

[20 40 60 80]


s designed for numerical operations.

You can do:

arr + 5
arr * 2
arr / 10
arr ** 2

without manually looping.

This idea will become very important when we reach vectorization.

In [3]:
import numpy as np
arr=np.array([2,4,6,8,10])
print(arr)
print(arr+5)
print(arr*3)

[ 2  4  6  8 10]
[ 7  9 11 13 15]
[ 6 12 18 24 30]


In [7]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
#shape → structure/dimensions of the array
#ndim → number of dimensions
#size → total number of elements
#dtype → data type of elements

(5,)
1
5
int64


In [8]:
import numpy as np
arr=np.array([
    [10,20,30],
    [40,50,60]
])
print(arr)
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2
int64


In [10]:
import numpy as np
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr)
print(arr[0,0])
print(arr[1,1])
print(arr[1,2])
print(arr[0])
print(arr[1])
print(arr[:,2])
print(arr[0,1:])
print(arr[1,:2])
#arr[row_start:row_stop, col_start:col_stop]

[[10 20 30]
 [40 50 60]]
10
50
60
[10 20 30]
[40 50 60]


arr[0, 0]       # specific element
arr[0]          # entire row
arr[:, 2]       # entire column
arr[0, 1:]      # part of a row
arr[1, :2]      # part of a row

arr[row_start:row_stop, col_start:col_stop]  # 2D slicing

In [12]:
#Reshaping
import numpy as np
arr=np.array([10,20,30,40,50,60])
arr2=arr.reshape(2,3)
print(arr2)
print(arr2.shape)

[[10 20 30]
 [40 50 60]]
(2, 3)


In [15]:
import numpy as np
print(np.zeros(5))
print(np.ones((2,3)))
print(np.arange(1,11))
print(np.arange(2,10,2))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [16]:
# Array Opeartions
import numpy as np
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a**2)

[12 24 35]
[ 8 16 25]
[ 20  80 150]
[5. 5. 6.]
[100 400 900]


In [17]:
#  7️⃣ Aggregation Functions

#Aggregation means taking many values and producing a summary value.

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

150
30.0
50
10
14.142135623730951


In [18]:
#axis=0 → operate DOWN the rows
#axis=0 → column-wise result
#axis=1 → row-wise result
import numpy as np
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))



[50 70 90]
[ 60 150]
[25. 35. 45.]
[20. 50.]


In [20]:
#Boolean Masking & Filtering
import numpy as np
arr=np.array([10,25,30,45,50])
print(arr[arr>30])
print(arr[arr<25])
print(arr[(arr>=20)&(arr<=40)])

[45 50]
[10]
[25 30]


In [21]:
# Broadcasting
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr + 5)
print(arr * 2)

values = np.array([1, 2, 3])
print(arr + values)

[[15 25 35]
 [45 55 65]]
[[ 20  40  60]
 [ 80 100 120]]
[[11 22 33]
 [41 52 63]]


**NUMPY VECTORIZATION IS THE MAIN CHARACTER FOR NUMERICAL PYTHON**